version: '2'

services:
  web:
    image: nginx:latest
    ports:
      - "80:80"
    volumes:
      - "./:/app"
      - "./jjindo.conf:/etc/nginx/conf.d/default.conf"
    links:
      - php
    depends_on:
      - php
  php:
    image: php:7.2-fpm
    volumes:
      - "./:/app"